crestalnetwork/intentkit

CHANGELOG.md
app/config/config.py
app/core/ai.py
app/entrypoints/twitter.py
app/models/agent.py
docs/twitter.md

Change twitter config behavior

Fix: twitter config

---

app/entrypoints/tg.py
tg/bot/filter/content_type.py
tg/bot/kind/ai_relayer/router.py
tg/bot/pool.py

Feat / Telegram On the fly Agent Token Change 

---

app/core/ai.py
app/entrypoints/tg.py

Fix: wallet prompt

---

app/entrypoints/tg.py
tg/bot/filter/chat_type.py
tg/bot/filter/content_type.py
tg/bot/filter/id.py
tg/bot/filter/no_bot.py
tg/bot/kind/ai_relayer/router.py
tg/bot/pool.py
tg/bot/types/agent.py
tg/bot/types/bot.py

Validate database data, before adding the token to the list of bots.
Define new type for bot pool item.

Fix / Telegram validate database data

---

app/entrypoints/tg.py
tg/bot/kind/ai_relayer/router.py
tg/bot/pool.py
tg/bot/types/agent.py
tg/bot/types/bot.py
tg/bot/types/kind.py
tg/utils/cleanup.py

- Handle `aiohttp` error while stopping the bot and detachment of the webhook. 
- Remove the bot username while being tagged.
- Cleanup the bot token.
Closes #25

Fix / Telegram `aiohttp` error handle

---

tg/bot/kind/ai_relayer/router.py
tg/bot/types/bot.py

Refactor / Set default ai_relayer bot greeting to gmath

---

app/core/engine.py
app/entrypoints/web.py
app/models/agent.py

* prompt append
* prompt debug
* thread debug

Feat: prompt append

---

CHANGELOG.md
README.md
abstracts/skill.py
app/config/config.py
app/core/engine.py
app/core/skill.py
app/models/agent.py
app/models/db.py
app/models/skill.py
docs/contributing/skills.md
skills/twitter/__init__.py
skills/twitter/base.py
skills/twitter/get_mentions.py
skills/twitter/get_timeline.py

Refactor: skills architecture

---

app/core/engine.py
skills/enso/__init__.py
skills/enso/wallet.py

Enso wallet skill for querying the wallet balances and approvals

Feat: enso wallet approvals and balances query

---

app/admin/api.py
skills/twitter/base.py
skills/twitter/follow_user.py
skills/twitter/get_mentions.py
skills/twitter/get_timeline.py
skills/twitter/like_tweet.py
skills/twitter/post_tweet.py
skills/twitter/reply_tweet.py
skills/twitter/retweet.py
skills/twitter/search_tweets.py

Fix: twitter limit

---

README.md

docs(readme): minor fix on typo and path

---

.github/workflows/lint.yml
CHANGELOG.md
README.md
app/admin/api.py
docs/create_agent.sh
models/agent.py
poetry.lock
pyproject.toml
utils/middleware.py

Improve: admin jwt

---

skills/enso/networks.py
skills/enso/route.py
utils/random.py

Modify route API output to have the same result for Deposit and Swap.
Add tx reference code to the output to be used for the confirmation of the transaction data via cdp wallet.

Fix: enso route api output compacted

---

app/admin/api.py
app/core/engine.py
models/agent.py
skills/enso/__init__.py
skills/enso/prices.py
skills/enso/route.py
skills/enso/tokens.py
skills/enso/wallet.py
utils/middleware.py

better admin api for agent get and create

Feat: admin agent api

---

app/admin/api.py
app/entrypoints/twitter.py
models/agent.py
poetry.lock
pyproject.toml

Improve: admin api agent

---

app/api.py
app/services/twitter/client.py
app/services/twitter/oauth2.py
app/services/twitter/oauth2_callback.py

2 bug
1 feature: twitter auth api

Fix: twitter refresh bug

---

CHANGELOG.md
docker-compose.yml
models/agent.py
utils/middleware.py

Improve: jwt auth

---

abstracts/graph.py
app/core/engine.py
app/core/graph.py
skills/twitter/base.py
skills/twitter/follow_user.py
skills/twitter/get_mentions.py
skills/twitter/get_timeline.py
skills/twitter/like_tweet.py
skills/twitter/post_tweet.py
skills/twitter/reply_tweet.py
skills/twitter/retweet.py
skills/twitter/search_tweets.py

Improve: chat log

---

app/api.py
app/autonomous.py
app/config/config.py
app/telegram.py
app/twitter.py
poetry.lock
pyproject.toml

Feat: sentry

---

.github/workflows/build.yml
CHANGELOG.md

Fix: release

---

app/services/twitter/client.py

Fix: twitter userinfo

---

app/services/twitter/client.py

Fix: a twitter client data cache bug

---

app/admin/api.py
app/entrypoints/web.py
app/services/twitter/oauth2.py

Fix: change all api handler async

---

app/admin/api.py
app/core/api.py
app/core/engine.py
models/skill.py

Cleanup the agent memory or a thread of an agent.

Feat: Agent memory cleanup

---

app/services/tg/bot/pool.py

refactor: tg init bot error message type to info

---

app/core/engine.py
docs/create_agent.sh
models/agent.py
poetry.lock
skills/enso/route.py
skills/enso/wallet.py

Feat: llm creative

---

app/config/config.py
app/core/engine.py

Refactor: move rpc config to env

---

app/admin/api.py
app/admin/health.py
app/api.py
app/entrypoints/web.py
app/readonly.py
models/chat.py
poetry.lock
pyproject.toml

Improve: readonly api

---

app/admin/api.py
app/core/engine.py
models/agent.py
models/skill.py

Fix: agent memory cleanup

---

utils/middleware.py

fix: jwt-readonly

---

.github/workflows/build.yml
app/core/engine.py
app/services/twitter/oauth2.py

Fix: twiiter binding

---

app/core/engine.py

Fix: Clean memory async call

---

app/core/engine.py
skills/enso/__init__.py
skills/enso/base.py
skills/enso/networks.py
skills/enso/prices.py
skills/enso/route.py
skills/enso/tokens.py
skills/enso/wallet.py

Feat: Enso skills async

---

app/entrypoints/tg.py
app/services/tg/bot/kind/ai_relayer/router.py

Fix: telegram async agent execute

---

.github/PULL_REQUEST_TEMPLATE.md

Fix: github pr template remove title

---

app/core/client.py
app/services/tg/bot/kind/ai_relayer/router.py
app/singleton.py

Add a singleton service for twitter auth and callback

Fix: twitter auth link

---

.github/workflows/build.yml
abstracts/twitter.py
app/core/engine.py
app/services/twitter/client.py
app/services/twitter/oauth2_callback.py
app/services/twitter/oauth2_refresh.py
models/skill.py
poetry.lock
skills/twitter/follow_user.py
skills/twitter/get_mentions.py
skills/twitter/get_timeline.py
skills/twitter/like_tweet.py
skills/twitter/post_tweet.py
skills/twitter/reply_tweet.py
skills/twitter/retweet.py
skills/twitter/search_tweets.py

Fix: twiiter refresh bug

---

app/core/engine.py
docs/create_agent.sh
models/agent.py
skills/acolyt/__init__.py
skills/acolyt/ask.py
skills/acolyt/base.py

Feat: Acolyt gpt chat integration

---

app/entrypoints/tg.py
app/services/tg/bot/pool.py
docs/create_agent.sh
models/agent.py

Fix: telegram_enabled changed to telegram_entrypoint_enabled

---

docs/how_to/clean_memory.md
docs/how_to/readme.md

Doc: agent's memory cleanup

---

CHANGELOG.md
app/services/twitter/oauth2.py
app/services/twitter/oauth2_callback.py
skills/acolyt/ask.py

Improve: small fixes

---

app/services/twitter/oauth2.py
app/services/twitter/oauth2_callback.py

Fix: rename result_uri to redirect uri

---

app/admin/api.py
app/core/engine.py
models/agent.py

fix: auto create cdp wallet when create agent

---

app/admin/api.py
poetry.lock

fix more bug in wallet auto create.

Fix: wallet create

---

app/admin/api.py

fix: add agent request log

---

app/services/tg/bot/kind/ai_relayer/router.py

Fix: a bug in tg text process

---

app/services/tg/bot/kind/ai_relayer/router.py

fix: a tg message bug

---

app/admin/api.py

Handle telegram bot unauthorized error in create/update api.

Fix: api telegram unauthorized error code

---

app/core/engine.py

Move all of the steps of goat engine to a single try-except

Fix: move all goat engine steps to single try except

---

app/core/engine.py
app/entrypoints/web.py

Improve: skill error handling

---

app/admin/api.py

Handle TokenInvalid and Conflict errors in the telegram bot initiation in API.

Fix: api telegram handle token invalid

---

app/config/config.py
app/core/engine.py

Check chain provider attribute of the config instead of None check.

Fix: check chain_provider attribute for presence

---

DEVELOPMENT.md
abstracts/skill.py
app/core/engine.py
docs/skills/x.md
models/agent.py
models/skill.py
skills/twitter/get_mentions.py
skills/twitter/get_timeline.py
skills/twitter/search_tweets.py
utils/logging.py

Feat: json schema part 1.5

---

app/api.py
app/autonomous.py
app/config/config.py
app/core/engine.py
app/scheduler.py
app/singleton.py
app/telegram.py
app/twitter.py
skills/enso/route.py
skills/enso/wallet.py

sentry rate limit
better prompt

Fix: sentry rate

---

app/core/engine.py

fix: cdp bug

---

app/core/engine.py

Fix: cdp skills load bug

---

app/admin/api.py
app/entrypoints/web.py
models/agent.py

Improve: debug things

---

app/api.py
app/autonomous.py
app/core/engine.py
app/readonly.py
app/scheduler.py
app/singleton.py
app/telegram.py
app/twitter.py
models/agent.py
poetry.lock

Fix: agentkit issues

---

app/core/engine.py

Fix: prompt hack for agentkit

---

app/core/engine.py
app/core/prompt.py
app/entrypoints/web.py
skills/cdp/get_balance.py

Fix: agentkit bug

---

app/admin/api.py
app/config/config.py
app/core/engine.py

auto clean memory when agent update.

Feat: clean memory after agent update

---

app/core/engine.py
docs/create_agent.sh
models/agent.py
skills/elfa/__init__.py
skills/elfa/base.py
skills/elfa/mention.py
skills/elfa/stats.py
skills/elfa/tokens.py

This PR introduces Five new LangChain tools that leverage the Elfa API to retrieve social media data:
*   `ElfaGetMentions`: Queries hourly-updated tweets from "smart accounts" (influential accounts with 10+ interactions). Useful for real-time trend analysis, competitor monitoring, influencer tracking, and reputation management.
*   `ElfaGetTopMentions`: Queries tweets mentioning a specific stock ticker, ranked by view count.  Provides insights into real-time market sentiment, trending news, and investor discussions.
*   `ElfaSearchMentions`: Searches tweets for up to five keywords within a specified timeframe (30 days current, 6 months historical).  Enables market research, brand monitoring, public opinion tracking, and …

Feat: Elfa integration

---

docs/create_agent.sh

Fix misspelled lowercase variable in the `create_agent.sh`

Fix: create_agent elfa skills lowercase

---

app/entrypoints/web.py
models/chat.py
skills/elfa/mention.py
skills/elfa/stats.py
skills/elfa/tokens.py

feat: chat list api

---

app/admin/api.py
app/admin/schema.py
app/core/api.py
app/entrypoints/web.py
app/services/twitter/oauth2.py
app/services/twitter/oauth2_callback.py
models/chat.py
utils/logging.py

Feat: multi chats

---

CHANGELOG.md
app/admin/api.py
app/admin/schema.py
app/core/engine.py
app/core/graph.py
app/entrypoints/web.py
app/services/twitter/oauth2_callback.py
skills/twitter/get_mentions.py
skills/twitter/search_tweets.py
utils/slack_alert.py

Fix: prod bugs

---

app/admin/api.py
app/admin/scheduler.py
app/autonomous.py
app/config/config.py
app/core/agent.py
app/core/api.py
app/core/client.py
app/core/engine.py
app/core/skill.py
app/entrypoints/autonomous.py
app/entrypoints/tg.py
app/entrypoints/twitter.py
app/entrypoints/web.py
app/services/tg/bot/kind/ai_relayer/router.py
app/services/twitter/oauth2_refresh.py
models/agent.py
models/agent_schema.json
models/base.py
models/chat.py
models/db.py
models/db_mig.py
models/skill.py
poetry.lock
pyproject.toml
skills/common/__init__.py
skills/common/base.py
skills/common/current_time.py
skills/common/schema.json
skills/twitter/__init__.py
utils/logging.py

* multiple autonomous
* skill execution log
* sqlalchemy refactor

Feat: multi autonomous

---

models/agent.py
models/chat.py
models/skill.py

Fix: updated_at but in sqlalchemy

---

app/admin/api.py
app/entrypoints/web.py
models/agent.py
models/chat.py
models/db.py
models/db_mig.py
models/skill.py
poetry.lock

split agent create and update api
bug fixes

Feat: split agent create and update api

---

app/admin/api.py
app/api.py
models/agent.py

Feat: agent etag

---

app/admin/api.py
app/autonomous.py
app/core/engine.py
app/entrypoints/autonomous.py
app/entrypoints/twitter.py
app/entrypoints/web.py
app/services/tg/bot/kind/ai_relayer/router.py
models/chat.py

- add user id to chat message
- add optional query param to chat history api

Feat: add user id to chat message

---

DEVELOPMENT.md
README.md
docs/README.md
docs/contributing/wishlist.md

docs: add wishlist information

---

app/admin/api.py
models/agent.py

fix: agent empty id issue

---

models/agent.py
poetry.lock

Fix: a upstream id check bug

---

app/core/engine.py

Fix: skill bug

---

models/agent.py
models/agent_schema.json

Fix: prompt limit

---

app/core/engine.py
app/core/graph.py
models/agent.py
models/agent_schema.json
poetry.lock
pyproject.toml
skills/base.py
skills/common/current_time.py

Fix: skill context bug

---

Dockerfile

Fix: dockerfile

---

Dockerfile

Fix: ci bug

---

app/core/engine.py
app/services/twitter/oauth2_refresh.py
skills/acolyt/ask.py
skills/allora/__init__.py
skills/allora/base.py
skills/allora/price.py
skills/base.py
skills/cryptocompare/__init__.py
skills/cryptocompare/base.py
skills/cryptocompare/fetch_news.py
skills/cryptocompare/fetch_price.py
skills/cryptocompare/fetch_top_exchanges.py
skills/cryptocompare/fetch_top_market_cap.py
skills/cryptocompare/fetch_top_volume.py
skills/cryptocompare/fetch_trading_signals.py
skills/elfa/__init__.py
skills/elfa/base.py
skills/elfa/mention.py
skills/elfa/stats.py
skills/elfa/tokens.py
skills/slack/__init__.py
skills/slack/get_channel.py
skills/slack/get_message.py
skills/slack/schedule_message.py
skills/slack/send_message.py
skills/twitter/get_timeline.py

Fix: skill bugs

---

app/core/api.py
models/agent_schema.json

fix: tg bug

---

models/agent.py
models/agent_schema.json

fix: agent name length limit

---

app/core/engine.py
skills/base.py

Fix: skill context issue

---

app/core/skill.py
poetry.lock

fix: skill data bug

---

clients/twitter.py

Fix: twitter client bug

---

skills/twitter/search_tweets.py

fix: a twitter skill bug

---

app/config/config.py

fix: redis port type

---

app/admin/scheduler.py
app/autonomous.py
app/core/engine.py
app/entrypoints/autonomous.py
app/entrypoints/twitter.py
app/entrypoints/web.py
app/scheduler.py
app/services/tg/bot/kind/ai_relayer/router.py
models/chat.py
poetry.lock
pyproject.toml

[add thread type and reply_to to chat messages](https://github.com/crestalnetwork/intentkit/commit/65b67c152af4c0f163160b29251d3fa683447134)

Feat: add thread type and reply_to to chat messages

---

skills/allora/__init__.py
skills/cryptocompare/__init__.py
skills/elfa/__init__.py

fix: some skills

---

app/services/tg/bot/kind/ai_relayer/router.py

improve: tg markdown

---

app/services/tg/bot/kind/ai_relayer/router.py

fix: tg markdown format issue

---

app/services/tg/bot/kind/ai_relayer/router.py

fix: another tg bug

---

app/services/tg/bot/kind/ai_relayer/router.py
poetry.lock
pyproject.toml

fix: telegram markdown format converter

---

app/admin/api.py
app/services/tg/bot/kind/ai_relayer/router.py

fix: agent create bug

---

.gitignore
DEVELOPMENT.md
README.md
docs/README.md
docs/agent.md
models/agent.py
scripts/create.sh
scripts/export.sh
scripts/import.sh

doc: agent management

---

DEVELOPMENT.md
app/admin/api.py
poetry.lock

fix: agent get bug

---

app/entrypoints/web.py

fix: a bug of debug api

---

app/admin/__init__.py
app/admin/credit.py
app/api.py
app/core/engine.py
models/credit.py

feat: credit model

---

lint.sh
models/agent.py
models/agent_schema.json
poetry.lock
pyproject.toml

feat: new agent fields

---

models/agent_schema.json

fix: json schema

---

app/core/engine.py
scripts/batch_migrate_skills.py

fix: skill backward compatibility

---

app/admin/api.py
models/agent_schema.json
poetry.lock
pyproject.toml
skills/acolyt/__init__.py
skills/allora/__init__.py
skills/cryptocompare/__init__.py
skills/defillama/tvl/fetch_protocols.py
skills/elfa/__init__.py
skills/enso/__init__.py
skills/enso/schema.json

improve: export agent

---

app/admin/credit.py

fix: fastapi doc bug

---

skills/cdp/schema.json
skills/defillama/schema.json

fix: json schema of skills

---

skills/moralis/README.md
skills/moralis/__init__.py
skills/moralis/fetch_blockchain_data.py
skills/moralis/fetch_blockchain_transaction.py
skills/moralis/fetch_transaction_history.py
skills/moralis/schema.json

add new functions to skill moralis 
fix bug on transaction history

chore(skills): refactor and update moralis skills

---

app/core/engine.py
app/services/tg/bot/types/bot.py
models/agent.py
models/agent_schema.json

fix: telegram config

---

models/agent.py

fix: dep bug in agent model

---

app/admin/api.py
app/core/engine.py
app/core/prompt.py
clients/cdp.py

fix: wallet provider bug

---

app/core/prompt.py

fix: a prompt bug

---

app/admin/schema.py
app/core/engine.py
app/entrypoints/autonomous.py
app/entrypoints/web.py
poetry.lock

feat: auto owner mode

---

app/admin/api.py
app/autonomous.py
models/agent.py
poetry.lock
pyproject.toml

fix: autonomous check

---

app/core/engine.py
models/agent.py
models/agent_schema.json

fix: json schema bug

---

app/config/config.py
poetry.lock
skills/acolyt/schema.json
skills/allora/schema.json
skills/cdp/schema.json
skills/common/__init__.py
skills/common/heurist_image_generation.py
skills/common/image_to_text.py
skills/common/schema.json
skills/cryptocompare/schema.json
skills/defillama/schema.json
skills/elfa/schema.json
skills/enso/schema.json
skills/moralis/schema.json
skills/slack/schema.json
skills/twitter/schema.json

feat: Heurist

---

app/config/config.py
models/agent_schema.json

feat: add skill index

---

models/agent.py

feat: accept image flag

---

skills/acolyt/schema.json
skills/allora/schema.json
skills/cdp/schema.json
skills/common/schema.json
skills/cryptocompare/__init__.py
skills/cryptocompare/base.py
skills/cryptocompare/fetch_news.py
skills/cryptocompare/fetch_price.py
skills/cryptocompare/fetch_top_exchanges.py
skills/cryptocompare/fetch_top_market_cap.py
skills/cryptocompare/fetch_top_volume.py
skills/cryptocompare/fetch_trading_signals.py
skills/cryptocompare/schema.json
skills/defillama/schema.json
skills/elfa/schema.json
skills/enso/schema.json
skills/heurist/schema.json
skills/moralis/schema.json
skills/openai/__init__.py
skills/openai/dalle_image_generation.py
skills/openai/image_to_text.py
skills/openai/schema.json
skills/slack/schema.json
skills/twitter/schema.json

feat: api key flag

---

.github/workflows/lint.yml
app/admin/api.py
app/core/engine.py
clients/twitter.py
lint.sh
models/agent_schema.json

chore: sync prod fix

---

app/services/tg/bot/kind/ai_relayer/router.py
models/chat.py

fix: message length and tg message track

---

poetry.lock
pyproject.toml
skills/cryptocompare/schema.json
skills/moralis/schema.json
skills/slack/schema.json
skills/tavily/schema.json

fix: schema dependentRequired

---

skills/cryptopanic/schema.json

fix: more crypto panic schema

---

models/agent_schema.json

fix: enable crypto panic

---

app/admin/credit.py
app/core/credit.py
models/agent_schema.json
models/credit.py

feat: credits part 1

---

abstracts/api.py
app/admin/api.py
app/admin/credit.py
models/credit.py

fix: auto create credit account

---

poetry.lock
pyproject.toml

chore: update dep

---

app/admin/credit.py
app/config/config.py
app/core/credit.py
app/core/engine.py
models/agent.py
models/agent_schema.json
models/credit.py

* payment settings in config
* expense credits when chat
* fix events list bugs
still missing:
* handle tg/twitter entrypoints payment to owner
* auto refill hourly
* pricing admin

feat: payment part 2

---

app/admin/scheduler.py
app/core/credit.py
app/core/engine.py

feat: auto refill caps

---

skills/nation/schema.json

optimize nation schema

---

app/admin/credit.py
app/core/credit.py
app/core/engine.py
models/agent.py
models/agent_schema.json
skills/nation/schema.json

feat: gpt 4.1

---

models/chat.py
skills/dapplooker/__init__.py

fix: 2 type define bug

---

models/credit.py

fix: credit account auto create bug

---

app/readonly.py
skills/tavily/schema.json

fix: credit router bug

---

app/core/engine.py
models/agent.py
models/chat.py
models/credit.py
skills/heurist/image_generation_animagine_xl.py
skills/heurist/image_generation_arthemy_comics.py
skills/heurist/image_generation_arthemy_real.py
skills/heurist/image_generation_braindance.py
skills/heurist/image_generation_cyber_realistic_xl.py
skills/heurist/image_generation_flux_1_dev.py
skills/heurist/image_generation_sdxl.py

fix: decimal bug

---

.gitignore
app/admin/credit.py
app/core/credit.py
models/skill.py
scripts/generate_skill_csv.py

feat: get credit event by id

---

app/admin/credit.py
app/core/credit.py

fix: credit events list resp pagination change

---

app/admin/credit.py

feat: add 403 auth to credit event aip

---

app/admin/credit.py
app/entrypoints/web.py
models/chat.py

feat: get message by id

---

skills/dapplooker/README.md
skills/dapplooker/dapplooker_token_data.py
skills/dapplooker/schema.json

Added complete token holder insights, developer wallet analysis, enhanced market metrics, and improved error handling for non-AI tokens. Updated documentation to clarify DappLooker's focus on AI agent tokens rather than general cryptocurrencies.
After the update

fix: adding more data fields for DappLooker skill

---

models/agent_schema.json

fix: hide agent fee

---

models/agent_schema.json
poetry.lock
pyproject.toml

fix: bug of filetype

---

app/core/engine.py
models/agent_schema.json

feat: payment agent whitelist

---

app/admin/__init__.py
app/admin/metadata.py
app/api.py
app/core/api.py
app/readonly.py
app/singleton.py

feat: metadata api

---

models/agent.py
models/agent_schema.json
skills/openai/__init__.py
skills/openai/gpt_image_generation.py
skills/openai/gpt_image_to_image.py
skills/openai/schema.json

feat: gpt image

---

app/admin/credit.py
app/core/credit.py

feat: add time to credits event query

---

app/core/engine.py
poetry.lock

fix: redis is now required now

---

app/core/credit.py
models/credit.py

feat: add user id to credit event

---

app/entrypoints/twitter.py
models/agent.py

fix: autonomous interval

---

app/core/engine.py
models/agent_schema.json

fix: a executor bug for skill list resp error

---

skills/twitter/get_mentions.py

fix: tmp change x mention limit

---

models/agent_schema.json
skills/twitter/post_tweet.py
skills/twitter/reply_tweet.py

fix: twitter skill prompt

---

app/admin/credit.py
app/core/credit.py

fix: add [start,end) to credit events api

---

app/core/prompt.py
skills/twitter/get_mentions.py
skills/twitter/get_timeline.py
skills/twitter/search_tweets.py

fix: prompt about not retry

---

skills/twitter/get_mentions.py
skills/twitter/get_timeline.py
skills/twitter/search_tweets.py

fix: try new twitter skill resp format

---

app/config/config.py
app/core/credit.py
app/core/engine.py

fix: message credit cost bug

---

skills/twitter/__init__.py
skills/twitter/get_mentions.py
skills/twitter/get_timeline.py
skills/twitter/get_user_by_username.py
skills/twitter/schema.json
skills/twitter/search_tweets.py

feat: twitter get user and avatar

---

app/admin/credit.py
app/core/engine.py
models/agent_schema.json
models/credit.py
skills/acolyt/schema.json

feat: agent credit statistics

---

models/agent_schema.json
models/llm.py

chore: hide for 1.9

---

models/agent.py

fix: hide agent info from api

---

.github/workflows/build.yml

fix: remove twitter deploy

---

skills/twitter/follow_user.py
skills/twitter/get_mentions.py
skills/twitter/get_timeline.py
skills/twitter/get_user_by_username.py
skills/twitter/like_tweet.py
skills/twitter/post_tweet.py
skills/twitter/reply_tweet.py
skills/twitter/retweet.py
skills/twitter/schema.json
skills/twitter/search_tweets.py

fix: twitter skills

---

DEVELOPMENT.md
README.md
docs/contributing/skills.md
models/credit.py

fix: sync prod hot fix

---

app/core/credit.py
app/core/engine.py
utils/logging.py

feat: stop skill when insufficient balance

---

skills/dapplooker/dapplooker_token_data.py

Fixed DappLooker skill integration to properly handle token addresses. Extracted data correctly from nested JSON responses. Modified request parameters to include both token tickers and addresses when available.

fix: dapplooker formatting fix

---

models/agent.py
skills/acolyt/schema.json
skills/aixbt/schema.json
skills/allora/schema.json
skills/cdp/schema.json
skills/common/schema.json
skills/cryptocompare/schema.json
skills/cryptopanic/schema.json
skills/dapplooker/schema.json
skills/defillama/schema.json
skills/elfa/schema.json
skills/enso/schema.json
skills/github/schema.json
skills/heurist/schema.json
skills/moralis/schema.json
skills/nation/schema.json
skills/openai/base.py
skills/openai/dalle_image_generation.py
skills/openai/gpt_image_generation.py
skills/openai/gpt_image_to_image.py
skills/openai/image_to_text.py
skills/openai/schema.json
skills/slack/schema.json
skills/tavily/schema.json
skills/twitter/schema.json
skills/unrealspeech/schema.json
skills/venice_image/schema.json

feat: api_key_provider

---

app/admin/schema.py
models/llm.py
models/skill.py
poetry.lock

feat: enabled flag of llm and skills

---

app/admin/schema.py
app/config/config.py
app/core/credit.py

feat: skill control

---

app/admin/credit.py
app/core/credit.py
models/credit.py
skills/acolyt/schema.json
skills/allora/schema.json
skills/common/schema.json
skills/cookiefun/schema.json
skills/cryptocompare/schema.json
skills/cryptopanic/schema.json
skills/dapplooker/schema.json
skills/defillama/schema.json
skills/elfa/schema.json
skills/enso/schema.json
skills/github/schema.json
skills/heurist/schema.json
skills/nation/schema.json
skills/openai/schema.json
skills/slack/schema.json
skills/twitter/schema.json
skills/unrealspeech/schema.json
skills/venice_image/schema.json

fix: charge agent fee from owner too

---

app/admin/api.py
app/admin/credit.py
models/agent.py

feat: override agent api

---

app/core/credit.py

fix: a new bug for dev fee

---

app/core/credit.py

fix: agent fee

---

models/agent_schema.json

fix: slider

---

models/agent_schema.json
skills/portfolio/base.py
skills/portfolio/token_balances.py
skills/portfolio/wallet_approvals.py
skills/portfolio/wallet_history.py
skills/portfolio/wallet_net_worth.py
skills/portfolio/wallet_profitability.py
skills/portfolio/wallet_profitability_summary.py
skills/portfolio/wallet_stats.py
skills/portfolio/wallet_swaps.py

fix: moralis key

---

skills/portfolio/schema.json

fix: moralis schema

---

app/config/config.py
skills/tavily/base.py
skills/tavily/schema.json
skills/tavily/tavily_search.py

feat: tavily api key

---

models/agent.py

fix: autonomous prompt length check

---

app/core/credit.py

fix: remove owner agent fee

---

models/agent_schema.json

fix: max agent fee to 100

---

skills/twitter/get_mentions.py
skills/twitter/get_timeline.py
skills/twitter/post_tweet.py
skills/twitter/reply_tweet.py

fix: twitter skill bugs

---

app/core/credit.py
models/credit.py
models/user.py

feat: auto update refill quota by nft count

---

app/admin/account_checking.py
app/admin/api.py
app/admin/scheduler.py
app/checker.py

fix: account checking

---

app/admin/api.py
app/admin/credit.py
app/admin/user.py
app/services/tg/bot/kind/ai_relayer/router.py
app/services/tg/bot/types/bot.py
models/agent_schema.json
skills/github/schema.json

feat: nft in schema

---

.github/workflows/build.yml
app/admin/account_checking.py
app/checker.py

chore: sync prod checker fix

---

skills/tavily/README.md
skills/tavily/__init__.py
skills/tavily/schema.json
skills/tavily/tavily_extract.py

Tavily Extract skill by implementing API integration for retrieving full webpage content with proper auth, error handling, and formatted output display.
https://github.com/user-attachments/assets/65c3bfc2-a90d-428b-b387-4a95acb6c24b

feat: tavily extract skill added

---

app/admin/scheduler.py
app/core/credit.py
app/core/engine.py
app/entrypoints/autonomous.py
app/entrypoints/twitter.py
models/agent.py

feat: agent free income limit

---

app/core/engine.py

fix: limit code

---

app/core/engine.py

fix: error style

---

skills/token/schema.json

fix: token skills

---

docs/README.md
docs/agent.md
docs/contributing/skills.md

docs update for url change of sandbox ui

chore: docs update for url change of sandbox ui

---

app/entrypoints/web.py
poetry.lock
pyproject.toml

fix: debug auth

---

poetry.lock
pyproject.toml

chore: update langgraph

---

.github/workflows/build.yml
app/api.py
app/readonly.py
app/singleton.py
docker-compose.yml
utils/error.py

refactor: api error handling

---

app/admin/scheduler.py
app/core/agent.py
app/core/engine.py
models/agent.py

feat: avg cost

---

app/admin/account_checking.py
app/admin/api.py
app/core/credit.py

feat: better agent validator

---

models/agent_schema.json
models/credit.py
skills/twitter/__init__.py
skills/twitter/get_user_tweets.py
skills/twitter/schema.json

fix: twitter bugs

---

app/admin/credit.py

feat: permanent_income

---

app/admin/credit.py
app/admin/scheduler.py
app/core/agent.py
models/agent.py

feat: more avg action cost

---

models/agent.py

fix: quota table missing fields

---

app/admin/credit.py

feat: tx api

---

models/agent_schema.json

fix: agent schema bug

---

skills/cookiefun/README.md
skills/cookiefun/base.py
skills/cookiefun/get_account_details.py
skills/cookiefun/get_account_feed.py
skills/cookiefun/get_account_smart_followers.py
skills/cookiefun/get_sectors.py
skills/cookiefun/schema.json
skills/cookiefun/search_accounts.py

Updated API key handling to support both platform and agent-owner key providers, default is platform, and improved skill descriptions.

fix: default state for skills and better descriptions

---

skills/openai/schema.json

tmp: skill price schema example

---

app/admin/scheduler.py
app/autonomous.py
app/checker.py
models/redis.py

fix: heartbeat

---

app/autonomous.py

fix: autonomous heartbeat bug

---

app/autonomous.py

fix: bug in autonomous main

---

skills/cookiefun/base.py
skills/cookiefun/schema.json

removing nation hosted option for cookie.fun skill

feat: removing nation hosted option for cookie.fun skill

---

app/config/config.py
models/agent_schema.json
skills/chainlist/schema.json
skills/cookiefun/base.py
skills/cookiefun/schema.json
skills/cryptopanic/schema.json
skills/dexscreener/schema.json
skills/dune_analytics/fetch_kol_buys.py
skills/dune_analytics/fetch_nation_metrics.py
skills/dune_analytics/schema.json
skills/github/schema.json
skills/heurist/schema.json
skills/nation/schema.json
skills/openai/schema.json
skills/twitter/schema.json

feat: open cookie.fun

---

app/admin/credit.py
app/core/credit.py
models/credit.py

feat: patch event note

---

app/core/credit.py
models/agent.py
models/agent_schema.json
models/credit.py
uv.lock

feat: fee details

---

app/admin/schema.py
skills/openai/schema.json

feat: x-price-level in json schema

---

app/admin/agent_generator_api.py
app/admin/generator/README.md
app/admin/generator/llm_logger.py
app/admin/generator/utils.py

Improvements: 
1. Tag generation was returning the same tags every time due to low temperature (0.3), increased temperature from 0.3 to 0.8
2. Could only get all projects for a user, not specific project history, enhanced API to support both user_id and project_id parameters

fix: tags issue fixed and project_id added in chat history API for single prompt agent generation

---

app/core/engine.py
models/skill.py

feat: at skill in message

---

skills/chainlist/schema.json
skills/dexscreener/schema.json
skills/dune_analytics/schema.json

fix: skill json schema

---

app/admin/agent_generator_api.py
app/admin/generator/__init__.py
app/admin/generator/agent_generator.py
app/admin/generator/ai_assistant.py
app/admin/generator/conversation_service.py
app/admin/generator/llm_logger.py
models/conversation.py

The previous implementation stores conversation history in memory which will be lost when the application restarts. I created a proper database model for conversation history.

fix: proper database model for conversation history

---

app/core/node.py
models/agent_schema.json
uv.lock

fix: payment check bug

---

app/config/config.py
skills/system/get_api_key.py
skills/system/reset_api_key.py

fix: move to open_api_base_url

---

app/admin/agent_generator_api.py
app/admin/generator/conversation_service.py
app/admin/generator/skill_processor.py

- Make user_id required field in AgentGenerateRequest with validation
- Enhanced skill processor with schema-based configuration loading
- Added proper API key provider defaults from skill schemas

fix: require user_id in agent generation API and fix conversation history

---

app/core/engine.py

fix: re issue

---

app/core/engine.py
models/llm.py

feat: native search

---

models/llm.py

feat: search field in llm model

---

skills/lifi/token_quote.py

fix: lifi typo

---

app/admin/schema.py
app/core/engine.py
models/agent.py
models/llm.py
utils/error.py

refactor: llm base code

---

skills/lifi/schema.json

adding step value for the slider to work in LiFi skill

fix: adding step value for the slider to work in lifi skill

---

app/core/engine.py
models/agent_schema.json
skills/cookiefun/schema.json
skills/dune_analytics/schema.json
skills/elfa/schema.json
skills/tavily/schema.json

fix: some skill issues

---

intentkit/skills/web_scraper/scrape_and_index.py
intentkit/skills/web_scraper/utils.py
intentkit/skills/web_scraper/website_indexer.py

cloudflare bypass for web scraper skill

feat: cloudflare bypass for web scraper skill

---

app/admin/api.py
docker-compose.yml
example.env
intentkit/clients/cdp.py
intentkit/config/config.py
scripts/fix_invalid_wallets.py

AgentKit 0.6.0 CDP environment variables setup
- Add CDP environment variable configuration for AgentKit 0.6.0 compatibility
- Update config.py to load new CDP variables and set environment variables
- Update cdp.py to use config values with proper fallbacks

fix: agentkit 0.6.0 CDP environment variables setup

---

LLM.md
intentkit/config/config.py

This PR updates the LLM integration guide documentation and includes configuration improvements.
- Updated LLM.md with comprehensive integration guide
- Enhanced configuration documentation in config.py
- Added detailed ops guide for git commits and pull requests

docs: update llm integration guide and config documentation

---

intentkit/abstracts/skill.py
intentkit/core/skill.py
intentkit/models/skill.py
intentkit/skills/firecrawl/README.md
intentkit/skills/firecrawl/__init__.py
intentkit/skills/firecrawl/clear.py
intentkit/skills/firecrawl/schema.json
intentkit/skills/firecrawl/utils.py

added the firecrawl_clear_indexed_content skill to create corrupt data and start fresh for an agent.

feat: clear data skill added

---

CHANGELOG.md
LLM.md
intentkit/skills/http/schema.json
intentkit/skills/supabase/schema.json

This PR updates the LLM integration guide and skill schema configurations:
- Updated LLM.md with improved documentation
- Modified HTTP skill schema configuration
- Updated Supabase skill schema configuration
These changes improve the developer experience and ensure proper skill configuration.

feat: update llm guide and skill schemas

---

CHANGELOG.md
intentkit/clients/cdp.py
intentkit/core/node.py
intentkit/skills/cdp/get_balance.py
intentkit/skills/firecrawl/schema.json
intentkit/skills/supabase/__init__.py
intentkit/skills/supabase/base.py
intentkit/skills/supabase/delete_data.py
intentkit/skills/supabase/fetch_data.py
intentkit/skills/supabase/insert_data.py
intentkit/skills/supabase/invoke_function.py
intentkit/skills/supabase/schema.json
intentkit/skills/supabase/update_data.py
intentkit/skills/supabase/upsert_data.py
intentkit/skills/system/schema.json
intentkit/skills/tavily/schema.json
scripts/cdp_list_token_balances_example.py

This PR includes several improvements and fixes:
- **feat**: Add public key to supabase
- **fix**: Node log level adjustment
- **fix**: CDP get balance bug resolution
- **fix**: Close some default skills
- **doc**: Update changelog
These changes improve the supabase integration, fix critical bugs in CDP balance retrieval, adjust logging levels, and update documentation.

feat: add public key to supabase and various fixes

---

CHANGELOG.md
LLM.md
README.md
app/auth/__init__.py
app/entrypoints/agent_api.py
app/entrypoints/openai_compatible.py
app/services/twitter/oauth2.py
docs/README.md
docs/agent_api.md
docs/openai_compatible.md
intentkit/clients/twitter.py
intentkit/core/credit.py
intentkit/models/credit.py
intentkit/skills/system/read_agent_api_key.py
intentkit/skills/system/regenerate_agent_api_key.py
uv.lock

This PR includes several major improvements and fixes:
- Enhanced agent API with improved authentication and documentation
- Added agent_wallet_address field to credit event tracking
- New agent API sub-application with CORS and error handling
- Token-based authentication for agent API endpoints
- Public key support for Supabase integration
- Better API key skill descriptions
- Refactored Twitter service for improved functionality
- Updated documentation structure and content
- Enhanced chat API with optional user_id and agent.owner fallback
- Improved formatting in extract_text_and_images function
- Fixed CDP get balance functionality
- Resolved chat message typo
- Fixed wallet creation during agent creation
- Corrected Supabase link issues
- Improved node log level handling
- Updated …

feat: comprehensive agent api enhancements and authentication improvements

---

CHANGELOG.md
app/admin/api.py
app/api.py
docs/agent_api.md
intentkit/models/agent.py

This PR includes:
- **Documentation improvements**: Enhanced agent documentation for better clarity
- **Model fix**: Removed number field from agent model
- **Changelog update**: Updated changelog with recent changes
These changes improve the overall documentation quality and fix a model issue in the agent system.

doc: improve agent documentation and fix agent model

---

CHANGELOG.md
app/entrypoints/agent_api.py
intentkit/models/agent.py

This PR adds a new endpoint to retrieve current agent information and enhances the agent response model with EVM and Solana wallet address fields.
- **Agent Info Endpoint**: Added `GET /agent` endpoint to retrieve current agent information from JWT token
- **Wallet Address Support**: Extended `AgentResponse` model with `evm_wallet_address` and `solana_wallet_address` fields
- **ETag Support**: Added ETag header to agent response for caching optimization
- Added agent information retrieval endpoint in `app/entrypoints/agent_api.py`
- Enhanced `AgentResponse.from_agent()` method to include wallet addresses from agent data
- Improved code formatting in agent model response data update
- `app/entrypoints/agent_api.py`: New agent endpoint with ETag support
- `intentkit/models/agent.py`: Added …

feat: add agent info endpoint with wallet address support

---

CHANGELOG.md
intentkit/config/config.py
intentkit/models/db.py

This PR improves database connection pooling configuration with enhanced parameters for better connection management and performance.
- Added configurable connection pool parameters for PostgreSQL connections:
- `min_size` and `max_size` for pool sizing
- `timeout` and `max_idle` for connection timeout management
- `max_overflow`, `pool_timeout`, `pool_pre_ping`, and `pool_recycle` for SQLAlchemy engine optimization
- Enhanced connection health checks and recycling for better reliability
- Added `auto_migrate` configuration parameter to control automatic database migrations
- Added `pool_size` configuration parameter to set database connection pool size
- Default values: `auto_migrate=true`, `pool_size=3`
- Updated CHANGELOG.md with recent changes and version information
- **Better …

Improve database connection pooling configuration

---

.github/workflows/build.yml
CHANGELOG.md
intentkit/pyproject.toml
intentkit/uv.lock

This PR adds the `jsonref` dependency to the intentkit package and updates the build workflow:
- Added `jsonref>=1.1.0` dependency to `intentkit/pyproject.toml`
- Updated `intentkit/uv.lock` with the new dependency
- Updated `.github/workflows/build.yml` build configuration
- Updated `CHANGELOG.md` with release notes
- Adds support for JSON reference resolution in the intentkit package
- Maintains backward compatibility

feat: add jsonref dependency and update build workflow

---

CHANGELOG.md
LLM.md

This PR includes updates to documentation files:
- **CHANGELOG.md**: Consolidated and cleaned up changelog entries
- **LLM.md**: Updated LLM integration guide with latest information
These changes improve the documentation quality and provide better guidance for developers working with IntentKit.

docs: update changelog and llm documentation

---

app/entrypoints/agent_api.py
app/entrypoints/web.py
intentkit/clients/cdp.py
intentkit/core/credit.py
intentkit/models/agent_schema.json
intentkit/models/chat.py
intentkit/models/credit.py
scripts/check_credit_event_consistency.py
scripts/fix_credit_event_consistency.py
scripts/migrate_base_amounts.py

This PR includes several improvements and fixes:
- **Fix CDP network ID mapping**: Added network ID mapping hack for CDP mainnet networks (base, arbitrum, optimism, polygon, ethereum) to resolve CDP SDK compatibility issues
- **UI improvements**: Always hide skill details and improve onchain options descriptions
- **Credit system enhancements**: 
- Add base credit type amount fields with migration script
- Enhance credit events consistency checker and add fixer script
- Add event checking functionality
- ab128a1 fix: add network id mapping hack for cdp mainnet networks
- 8ee34c9 fix: always hide skill details
- 80a3454 fix: better onchain options desc
- c944dc2 feat(credit): add base credit type amount fields and migration script
- a70084f feat(credit-events): enhance consistency checker …

Fix CDP network ID mapping and enhance credit system

---

CHANGELOG.md
intentkit/clients/__init__.py
intentkit/clients/web3.py
intentkit/core/chat.py
intentkit/models/agent_schema.json
intentkit/skills/base.py

This PR introduces several enhancements to the IntentKit framework:
- **New Web3 Client**: Added `intentkit/clients/web3.py` to provide Web3 functionality
- **Client Module Updates**: Updated `intentkit/clients/__init__.py` to include the new web3 client
- **Core Chat Enhancement**: Added `intentkit/core/chat.py` for improved chat functionality
- **Skill System Improvements**: Enhanced `intentkit/skills/base.py` with better base functionality
- **Schema Updates**: Updated `intentkit/models/agent_schema.json` to reflect new capabilities
- **Documentation**: Updated `CHANGELOG.md` with recent changes
- `CHANGELOG.md` (modified)
- `intentkit/clients/__init__.py` (modified)
- `intentkit/clients/web3.py` (new)
- `intentkit/core/chat.py` (new)
- `intentkit/models/agent_schema.json` (modified)
- …

feat: add web3 client and enhance skill system

---

intentkit/models/agent_schema.json
intentkit/pyproject.toml
uv.lock

This PR includes several improvements and fixes:
- **feat: agent onchain fields** - Added onchain-related fields to agent schema
- **chore: upgrade** - Updated dependencies and configurations
- **fix: typo in intentkit package info** - Fixed typo in package information
- Enhanced agent model with onchain capabilities
- Package information corrections
- Dependency updates

feat: agent onchain fields and improvements

---

Dockerfile

This PR refactors the Dockerfile to improve build efficiency by combining dependency installation steps into a single RUN command.
- Combined multiple RUN commands for dependency installation into a single command
- Reduced Docker layer count for better build performance
- Maintained the same functionality while improving build efficiency
- `Dockerfile`: Simplified dependency installation process (1 insertion, 7 deletions)
[Compare changes](https://github.com/crestalnetwork/intentkit/compare/main...hyacinthus)

refactor: simplify dockerfile dependency installation process

---

scripts/check_credit_event_consistency_with_base.py
scripts/migrate_base_amounts.py

fix: migration

---

app/admin/account_checking.py
app/admin/credit.py
intentkit/core/credit.py
intentkit/models/credit.py
intentkit/models/db.py
intentkit/models/llm.py
intentkit/models/user.py
scripts/migrate_credit_account_statistics.py

This PR includes several improvements to the credit system:
- **Enhanced balance consistency check**: Added detailed verification in account checking with comprehensive balance validation
- **Improved decimal precision**: Ensured proper decimal quantization in credit calculations to maintain accuracy
- **Transaction statistics tracking**: Added comprehensive transaction statistics tracking to credit accounts
- **Database optimization**: Updated agent statistics to use direct permanent_profit field from database instead of calculated values
- Removed unnecessary ROUND_HALF_UP import and calculation logic
- Added fee_agent_permanent_amount field to statistics queries
- Improved error handling and validation in credit operations
- Enhanced data consistency checks across the credit system …

Credit system improvements and statistics enhancements

---

scripts/migrate_credit_account_statistics.py

This PR fixes the credit account statistics migration script by:
- Adding proper database initialization with `init_db(**config.db)`
- Improving the account filtering query to only migrate accounts that actually need migration (where all 8 statistics fields are 0)
- Adding proper imports for config and init_db
This ensures the migration script works correctly and only processes accounts that haven't been migrated yet, making it more efficient and preventing unnecessary processing.

fix: add database initialization and improve account filtering in migration script

---

intentkit/core/chat.py
intentkit/core/engine.py

This PR introduces automatic clearing of error memory to prevent error accumulation in the agent's memory.
- Added functionality to automatically clear error memory
- Improved memory management for better error handling

feat: auto clear error memory

---

intentkit/models/agent.py

This PR improves the agent response model validation and data conversion in the `AgentResponse` class.
- **Enhanced model configuration**: Added `use_enum_values=True` to the model config to properly handle enum serialization
- **Improved autonomous data handling**: Updated the autonomous field filtering to create proper `AgentAutonomous` instances instead of plain dictionaries, ensuring proper validation and type safety
- **Added examples data conversion**: Implemented proper conversion of examples dictionaries to `AgentExample` instances with validation
The changes ensure that when creating `AgentResponse` objects, all nested data structures are properly validated and converted to their respective Pydantic model instances rather than remaining as plain dictionaries. This improves type …

fix: improve agent response model validation and data conversion

---

app/admin/agent_generator_api.py
app/admin/api.py
app/admin/credit.py
app/admin/schema.py
app/admin/user.py
app/auth/__init__.py
app/entrypoints/agent_api.py
app/entrypoints/openai_compatible.py
app/entrypoints/web.py
app/services/twitter/oauth2_callback.py
intentkit/core/agent.py
intentkit/core/chat.py
intentkit/core/credit.py
intentkit/core/engine.py
intentkit/models/agent.py
intentkit/models/agent_data.py
intentkit/models/credit.py
intentkit/utils/error.py

This PR improves error handling across the IntentKit framework with two key fixes:
- Enhanced error handling for IntentKitAPIError in core components
- Improved error propagation and messaging
- Better handling of HTTP errors in API endpoints and services
- More robust error responses and status codes
- `app/admin/` - Admin API endpoints and services
- `app/auth/` - Authentication modules
- `app/entrypoints/` - API entrypoints including agent API and web endpoints
- `app/services/twitter/` - Twitter OAuth2 callback handling
- `intentkit/core/` - Core agent, chat, credit, and engine modules
- `intentkit/models/` - Agent, agent data, and credit models
- `intentkit/utils/error.py` - Error utility improvements
- `044935b` - fix: IntentKitAPIError
- `7c398e5` - fix: http errors
These changes …

fix: improve error handling for IntentKitAPIError and HTTP errors

---

app/admin/api.py
intentkit/core/agent.py
intentkit/models/agent.py

This PR includes code formatting improvements and cleanup:
- Fixed line formatting and spacing in agent.py and api.py
- Removed unused import statement
- Improved code readability with consistent formatting
Changes made:
- `app/admin/api.py`: Fixed line formatting
- `intentkit/core/agent.py`: Improved code formatting and spacing
- `intentkit/models/agent.py`: Removed unused json import and improved formatting

refactor: improve code formatting and remove unused import

---

app/admin/api.py
intentkit/core/agent.py

This PR enhances the agent deployment functionality by adding wallet processing and notification capabilities.
- **Enhanced return type**: Updated `deploy_agent` function to return a tuple of `(Agent, AgentData)` instead of just `Agent`
- **Added wallet processing**: Integrated `process_agent_wallet` function for both new agent creation and existing agent updates
- **Added notifications**: Integrated `send_agent_notification` to notify about agent deployment events
- **Improved error handling**: Added proper error handling for duplicate upstream IDs with meaningful error messages
- **Updated documentation**: Fixed return type documentation to reflect the new tuple return
- **Updated API response handling**: Modified the admin API to properly handle the new tuple return from `deploy_agent` …

feat: enhance agent deployment with wallet processing and notifications

---

intentkit/models/agent.py

This PR includes comprehensive improvements to the agent system with multiple enhancements and fixes:
- Enhanced agent deployment with wallet processing and notifications
- Improved agent response model validation and data conversion
- Added required field validation for agent name in JSON schema
- Refactored agent core architecture and model structure
- Updated agent model schema and added public schema
- Improved type annotations and error handling throughout the agent system
- Enhanced code formatting and removed unused imports
- Fixed variable naming conflicts and endpoint function naming
- Improved IntentKitAPIError handling and HTTP error management
- Fixed agent response handling
- Corrected variable names in deploy_agent function
- Fixed SQLite SQL compatibility issues
- Resolved …

feat: comprehensive agent system improvements and refactoring

---

app/admin/agent_generator_api.py
app/admin/api.py
app/admin/credit.py
app/admin/scheduler.py
app/admin/user.py
app/api.py
app/autonomous.py
app/checker.py
app/entrypoints/agent_api.py
app/entrypoints/openai_compatible.py
app/entrypoints/tg.py
app/entrypoints/web.py
app/readonly.py
app/scheduler.py
app/services/tg/bot/kind/ai_relayer/router.py
app/services/tg/bot/pool.py
app/services/tg/bot/types/agent.py
app/services/tg/bot/types/bot.py
app/services/twitter/oauth2.py
app/services/twitter/oauth2_callback.py
app/services/twitter/oauth2_refresh.py
app/singleton.py
app/telegram.py
intentkit/config/config.py
pyproject.toml

This PR fixes uvloop compatibility issues in the Telegram integration components.
- Updated import statements across multiple app modules to ensure proper uvloop compatibility
- Modified Telegram bot components to handle uvloop event loop properly
- Updated configuration handling for better async compatibility
- Added necessary dependencies to pyproject.toml
- **App modules**: Updated 23 files in the app/ directory with uvloop compatibility fixes
- **Config**: Updated intentkit/config/config.py for better async handling
- **Dependencies**: Updated pyproject.toml with required packages
Fixes uvloop compatibility issues that were causing problems with Telegram bot operations.
---
**Diff**: https://github.com/crestalnetwork/intentkit/compare/main...hyacinthus

fix: tg uvloop compatibility issues
