- .github/workflows/build.yml
> Fix: deploy version bug

- app/core/engine.py
- skills/enso/__init__.py
- skills/enso/route.py
Adds support for Enso API to get the swap route shortcuts in detail.
> Feat: enso api route get

- skills/enso/__init__.py
- skills/enso/prices.py
Adds integration to Enso API prices endpoint to retrieve the token price by chain ID and contract address of token
> Feat: enso api prices

- skills/enso/route.py
Add swap to the definition of enso route
> fix: enso route tool definition

- app/core/engine.py
- skills/cdp/__init__.py
- skills/cdp/base.py
- skills/cdp/tx.py
- skills/enso/route.py
- utils/tx.py
Enables CDP wallet smart contract call from the stored call data output from the Enso route API. 
This PR forces the agent to have enabled CDP, otherwise, Enso wallet skills would not be functional.
Closes #91
> Feat: CDP wallet and Enso integration

- models/db_mig.py
The async database migration won't work as expected because of thread overlapping, this PR fixes that issue by using the same connection for all of the migration trasks.
> Fix: db migration asyc compatible

- app/admin/__init__.py
- app/admin/user.py
- app/api.py
- app/core/prompt.py
- app/readonly.py
- models/user.py
> feat: user model and api

- models/agent.py
> fix: agent owner logic

- skills/portfolio/__init__.py
- skills/portfolio/wallet_nfts.py
Fixed a small bug in Portfolio Skill, due to which is was not being loaded in the system.
> fix: portfolio skills bug fix

- models/conversation.py
change single prompt agent generation table names.
`generator_conversation_messages` and `generator_conversation_projects`
> feat: change single prompt agent generation table names

- app/admin/schema.py
This PR fixes the skills path from 'skills' to 'intentkit/skills' and adds support for webp image format in the admin schema.
Changes:
- Updated base_path in get_skill_schema() to use correct 'intentkit/skills' path
- Updated base_path in get_skill_icon() to use correct 'intentkit/skills' path
- Added webp media type support for skill icons
> fix: correct skills path and add webp support in admin schema

- intentkit/models/agent.py
This PR makes the `number` field in the `AgentResponse` model optional by changing the type from `int` to `Optional[int]`.
- Modified `intentkit/models/agent.py` to make the auto-incrementing number field optional
- This allows for more flexible handling of agent responses where the number might not always be present
> fix: make agent response number field optional

- CHANGELOG.md
- LLM.md
- intentkit/skills/twitter/get_timeline.py
This PR improves the Twitter timeline skill by excluding replies from the timeline results by default.
- Added `exclude=["replies"]` parameter to the Twitter API call in `get_timeline.py`
- This provides cleaner timeline results by filtering out reply tweets
- Cleaner timeline data for agents
- Reduces noise in timeline results
- Focuses on original tweets and retweets rather than conversational replies
- The change uses the standard Twitter API parameter for excluding replies
- No breaking changes to existing functionality
> feat: exclude replies from twitter timeline by default

- CHANGELOG.md
- intentkit/core/agent.py
This PR fixes the serialization of autonomous tasks in agent operations to ensure proper JSON storage in the database.
- **Fix**: Ensure proper serialization of `AgentAutonomous` objects using `model_dump()` before storing in database
- **Fix**: Correct task comparison logic in `delete_autonomous_task` to use direct attribute access
- **Doc**: Update changelog
The changes address two issues in the autonomous task management:
1. **Serialization Issue**: In both `add_autonomous_task` and `delete_autonomous_task` functions, `AgentAutonomous` objects weren't being properly serialized to dictionaries before storage in the database. This could cause JSON serialization errors.
2. **Task Comparison**: Fixed the task ID comparison logic in `delete_autonomous_task` to properly access the `id` …
> Fix autonomous task serialization in agent operations

- CHANGELOG.md
- intentkit/skills/twitter/get_mentions.py
- intentkit/skills/twitter/get_timeline.py
- intentkit/skills/twitter/get_user_by_username.py
- intentkit/skills/twitter/get_user_tweets.py
- intentkit/skills/twitter/search_tweets.py
- **get_mentions**: Reduced interval from 59 to 15 seconds
- **get_timeline**: Changed from 3 requests per 24 hours to 1 request per 15 seconds  
- **get_user_tweets**: Changed from 3 requests per 24 hours to 1 request per 15 seconds
- **search_tweets**: Changed from 3 requests per 24 hours to 1 request per 15 seconds
- **get_user_by_username**: Kept existing limits (5 requests per 24 hours)
- Updated CHANGELOG.md with v0.6.7 release notes including autonomous task management features, agent information endpoints, and various improvements
These changes make Twitter API rate limiting more conservative and frequent, which should help prevent API quota exhaustion and provide better request distribution over time.
**Full diff**: https://github.com/crestalnetwork/intentkit/compare/main...hyacin …
> improve: adjust twitter skills rate limits for better api management

- .github/workflows/build.yml
- CHANGELOG.md
Update the GitHub Actions workflow to use the correct deployment name `sandbox-open` instead of `sandbox-api` for both dev and prod environments.
- Updated `.github/workflows/build.yml` to use `sandbox-open` deployment name
- Fixed kubectl set image commands for both testnet-dev and testnet-prod namespaces
- Verified the workflow configuration matches the actual deployment names
- No functional changes to the application logic
This fixes the deployment naming inconsistency in the CI/CD pipeline.
> fix: update sandbox deployment name in github workflow

- CHANGELOG.md
- intentkit/skills/xmtp/schema.json
This PR adds the missing XMTP swap and price skills to the schema.
> fix: add missing xmtp schema

- intentkit/models/chat.py
This PR adds an `error_type` field to the chat message model to support better error handling and categorization in system messages.
- Added `error_type` column to `ChatMessageTable` database model
- Added `error_type` field to `ChatMessageCreate` Pydantic model
- Updated the model to properly handle error type assignment
> feat: add error_type field to chat message model

- intentkit/skills/dexscreener/README.md
- intentkit/skills/dexscreener/__init__.py
- intentkit/skills/dexscreener/base.py
- intentkit/skills/dexscreener/get_pair_info.py
- intentkit/skills/dexscreener/get_token_pairs.py
- intentkit/skills/dexscreener/get_tokens_info.py
- intentkit/skills/dexscreener/schema.json
- intentkit/skills/dexscreener/search_token.py
- intentkit/skills/dexscreener/utils.py
**3 new skills added in Dexscreener**
1. get_pair_info - Get comprehensive data for a specific trading pair
Example: "Get detailed info for pair address 0xa43fe16908251ee70ef74718545e4fe6c5ccec9f on Ethereum"
2. get_token_pairs - Find all trading pairs/pools for a specific token
Example: "Find all trading pairs for token 0x1f9840a85d5af5bf1d1762f925bdaddc4201f984 on Ethereum"
3.  get_tokens_info - Analyze up to 30 tokens at once (perfect for portfolio analysis)
Example: "Get trading data for these tokens on Ethereum: 0x1f9840a85d5af5bf1d1762f925bdaddc4201f984,
0xa0b86a33e6180d93e26c8fffab74649b6b0d3c29"
> feat: dexscreener new skills

- CHANGELOG.md
- intentkit/skills/xmtp/base.py
- intentkit/skills/xmtp/price.py
- intentkit/skills/xmtp/swap.py
- intentkit/skills/xmtp/transfer.py
This PR expands the XMTP skills to support multiple blockchain networks instead of being limited to Base only.
- Updated XMTP transfer, swap, and price skills to support Ethereum, Polygon, Base, Arbitrum, and Optimism networks (both mainnet and testnet)
- Refactored network validation logic into shared methods in the base class
- Added comprehensive chain ID mapping for all supported networks
- Updated skill descriptions to reflect multi-network support
- Users can now perform XMTP operations across multiple popular blockchain networks
- Improved code reusability with shared network validation methods
- Better error messages for unsupported networks
> feat: expand xmtp skills to support multiple networks

- CHANGELOG.md
- intentkit/models/llm.py
This PR adds support for the `reasoning_effort` parameter when using GPT-5 models in the OpenAI LLM configuration.
- Added automatic setting of `reasoning_effort: "minimal"` for models starting with "gpt-5"
- This ensures proper configuration for GPT-5 reasoning models
- Code follows existing patterns in the OpenAI LLM class
- Linting passes with ruff format and check
> feat: add reasoning_effort parameter for gpt-5 models

- CHANGELOG.md
- app/admin/account_checking.py
This PR includes:
- **Code Style Improvement**: Moved asyncio import to the top of the file in `app/admin/account_checking.py` following Python import conventions
- **Documentation**: Updated changelog for v0.6.25 release
The import refactoring improves code organization by placing all imports at the beginning of the file as per PEP 8 guidelines.
> refactor: move asyncio import to top of file and update changelog

- CHANGELOG.md
- intentkit/core/credit.py
Fixed missing amount fields in CreditTransactionTable instantiations within the `refill_free_credits_for_account` function.
- Added `free_amount`, `reward_amount`, and `permanent_amount` field assignments to both user and platform transaction records in the refill function
- Ensures data consistency by properly setting all four amount fields (`change_amount`, `free_amount`, `reward_amount`, `permanent_amount`) for every CreditTransactionTable instantiation
The refill function was missing explicit assignments for the three amount breakdown fields, which could lead to incomplete transaction records. This fix ensures:
- `free_amount` is set to `amount_to_add` for free credit transactions
- `reward_amount` and `permanent_amount` are explicitly set to `Decimal("0")` when not applicable
- All …
> fix: add missing amount fields to CreditTransactionTable instantiations

- intentkit/skills/firecrawl/base.py
- intentkit/skills/firecrawl/schema.json
This PR adds support for platform-provided API keys in the Firecrawl skill, allowing users to choose between platform-hosted and owner-provided API key configurations.
- Updated `base.py` to handle platform API key provider by fetching from system config
- Modified `schema.json` to include "platform" as an API key provider option with "Nation Hosted" as the display name
- Changed default API key provider from "agent_owner" to "platform"
- Provides flexibility for users to choose their preferred API key configuration
- Enables platform-hosted API key management for better user experience
- Maintains backward compatibility with existing owner-provided configurations
> feat: add platform API key support for firecrawl skill

- intentkit/models/agent.py
- intentkit/models/agent_public.json
- intentkit/models/agent_schema.json
This PR refactors the agent model schema and adds a new public schema file.
- **Modified `intentkit/models/agent.py`**: Updated agent model structure with 393 lines changed
- **Added `intentkit/models/agent_public.json`**: New public schema file with 98 lines
- **Modified `intentkit/models/agent_schema.json`**: Updated existing schema with 97 lines removed
The changes involve restructuring the agent model to better separate public and internal schema definitions. This refactoring improves the organization of agent-related models and provides a cleaner public API interface.
**Files changed:**
- `intentkit/models/agent.py` (393 lines modified)
- `intentkit/models/agent_public.json` (98 lines added)
- `intentkit/models/agent_schema.json` (97 lines removed)
**Net changes:** +304 insertions, …
> refactor: update agent model schema and add public schema

- app/admin/api.py
- intentkit/models/agent.py
This PR includes two important fixes:
1. **Function rename**: Changed `deploy_agent` to `override_agent` in the admin API to better reflect the function's purpose
2. **Annotation syntax fix**: Updated `SkipJsonSchema` annotations in the `AgentResponse` model from `Annotated[Type, SkipJsonSchema]` to `SkipJsonSchema[Type]` for proper Pydantic v2 compatibility
- `app/admin/api.py`: Updated function call from `deploy_agent` to `override_agent`
- `intentkit/models/agent.py`: Fixed annotation syntax for privacy fields in `AgentResponse` class
These changes improve code clarity and ensure proper type annotation handling.
> fix: rename deploy_agent to override_agent and fix annotation syntax
